apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/deehstar/frontend:latest
          env:
            - name: BACKEND_PORT
              value: "9000"
            - name: BACKEND_DNS
              value: "backend-service"
          ports:
            - containerPort: 8080