name: Build Docker and Publish

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  GIT_COMMIT:  ${{ github.sha }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert GitHub actor to lowercase
        id: actor-lowercase
        run: echo "actor=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push frontend
        working-directory: ./frontend/
        run: |
          docker build . --tag ghcr.io/${{ env.actor }}/frontend:latest
          docker push ghcr.io/${{ env.actor }}/frontend:latest
