name: Build Docker and Publish

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  GIT_COMMIT:  ${{ github.sha }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:

  Build:
    

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert GitHub actor to lowercase
        id: actor-lowercase
        run: echo "actor=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Echo name
        run: echo "actor=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push frontend
        working-directory: ./frontend/
        run: |
          docker build . --tag ghcr.io/${{ env.actor }}/frontend:latest
          docker push ghcr.io/${{ env.actor }}/frontend:latest
