name: Main Workflow

on: 
  push:
  pull_request_target:
    branches: 
      - main
  branch_protection_rule:
    branches:
      - main
  

env:
  docker_username: henriikrc
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
  
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Go Environment
        uses: action/setup-go@v5.0.2
        with:
          go-version: '1.21'
      - name: Go Version
        run: go-version
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Build Backend
        working-directory: ./backend
        run: go build
      - name: Build Frontend
        working-directory: ./frontend
        run: go build
        
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go Environment
        uses: action/setup-go@v5.0.2
        with:
          go-version: '^1.21'
      - name: Test Application
        working-directory: ./frontend
        run: go test

